{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.metadata.name -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls}}
  - hosts: 
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{.secretName}}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.rules }}
    - host: {{.host }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          backend:
            serviceName: {{ .backend.serviceName }}
            servicePort: {{ .backend.servicePort }}
        {{- end }}
  {{- end }}
{{- end }}

